// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "1af3b4d0-bc6d-48e4-898a-6721a05187b9";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onMoistureTriggerChange();
void onPumpSwitchChange();
void onPlanterCommandChange();

int moistureLevel;
CloudPercentage moistureTrigger;
String planterStatus;
CloudSwitch pumpSwitch;
String planterCommand;
CloudPercentage moisturePercent;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(moistureLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moistureTrigger, READWRITE, ON_CHANGE, onMoistureTriggerChange);
  ArduinoCloud.addProperty(planterStatus, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pumpSwitch, READWRITE, ON_CHANGE, onPumpSwitchChange);
  ArduinoCloud.addProperty(planterCommand, READWRITE, ON_CHANGE, onPlanterCommandChange);
  ArduinoCloud.addProperty(moisturePercent, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
